baseURL = 'https://michaeldavidkelley.github.io/'
languageCode = 'en-us'
title = 'Rand0mb1ts'
theme = "cactus"
copyright = "Michael Kelley"

[params]
  colortheme="white"
  mainSection = "posts"
  mainSectionTitle = "Posts"
  showAllPostsOnHomePage = true
  showProjectList = true
